namespace ClinicalDecisionSupport.UI.Models;

public class FinalAssessmentModel
{
    public string PatientId { get; set; } = string.Empty;

    public string LeadingDiagnosis { get; set; } = string.Empty;
    public string Confidence { get; set; } = string.Empty;

    public List<string> SupportingEvidence { get; set; } = new();
    public List<string> SafetyAlerts { get; set; } = new();

    // Lab narrative synthesised by the consensus agent
    public string LabSummary { get; set; } = string.Empty;

    public List<TreatmentOptionModel> TreatmentOptions { get; set; } = new();

    // Runner-up diagnoses produced by the consensus agent
    public List<AlternativeDiagnosisModel> AlternativeDiagnoses { get; set; } = new();

    public Dictionary<string, string> AgentAgreement { get; set; } = new();
    public string Uncertainty { get; set; } = string.Empty;

    public List<CitationModel> Citations { get; set; } = new();

    // Safety disclaimer text generated by the LLM
    public string Disclaimer { get; set; } = string.Empty;
}